### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pajanne**

### CODE REVIEW

**Comment by pajanne** [comment]
GitHub desktop has changed slightly the 'Sync' icon in the top right corner has been replaced by a 'Publish' icon. Let me know if you wish me to re-do the print screens.

**Comment by pajanne** [comment]
Sorry my mistake... I did not publish the repo, so now I can see the 'Sync' icon. No action needed!

**Comment by pajanne** [comment]
Please let me know what you think about the new schedule and swapping original exercice 1 & 2. I'm planning to start with 'My first repo' within my presentation 'Github - What, Why & Welcome' and then after your presentation there'll be 'My first pull request' if you agree obviously! Let me know!

**Comment by KirstieJane** [comment]
Hi @pajanne - thanks for fixing so many typos! "My first pull request" is designed to come before "my first repo" because it doesn't require individual working - you're just following along the exact same steps as everyone else and we do it together (I have to stand at the front and merge the requests as they come in).

I'm going to merge this PR because you've made so many great changes already - but maybe we can talk about the schedule when we meet up :)

**Pull request merged**
